# 1. Import Libraries

In [2]:
# Data Manipulation
import pandas as pd
import numpy as np

# Data Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Preprocessing
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

# Classification Models
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier, StackingClassifier
from sklearn.linear_model import LogisticRegression

# Evaluation Metrics
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    confusion_matrix,
    classification_report
)
from imblearn.metrics import geometric_mean_score
# Model Saving
import joblib

In [3]:
print("Libraries imported successfully.")

Libraries imported successfully.


## 2: Loading the Dataset

In [4]:
df = pd.read_csv("../data/Delhi Accident Data.csv")
# Display first 5 rows
df.head()

C:\Users\moham\AppData\Local\Temp\ipykernel_9556\3893790449.py:1: DtypeWarning: Columns (0: Unnamed: 9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/Delhi Accident Data.csv")


,YEAR,DISTRICT,VEHICLE AT FAULT,VICTIM,TYPE OF ACCIDENT,# INJURED,# KILLED,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,2008,NORTH WEST DELHI,UNKNOWN,CAR,FATAL ACCIDENT,0,1,NaN,NaN,NaN
1,2008,NORTH WEST DELHI,UNKNOWN,CYCLE,SIMPLE ACCIDENT,1,0,NaN,NaN,NaN
2,2008,NEW DELHI,HTV/GDS,PEDESTRIAN,FATAL ACCIDENT,0,1,NaN,NaN,NaN
3,2008,EAST DELHI,S/C&M/C,PEDESTRIAN,SIMPLE ACCIDENT,1,0,NaN,NaN,NaN
4,2008,SHAHDARA,S/C&M/C,PEDESTRIAN,SIMPLE ACCIDENT,1,0,NaN,NaN,NaN


In [5]:
# Shape of the dataset
print("Rows and Columns:", df.shape)

Rows and Columns: (75748, 10)


In [6]:
# Column names
print(df.columns.tolist())

['YEAR', 'DISTRICT', 'VEHICLE AT FAULT', 'VICTIM', 'TYPE OF ACCIDENT', '# INJURED', '# KILLED ', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9']


In [7]:
# Basic information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 75748 entries, 0 to 75747
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   YEAR              75748 non-null  int64  
 1   DISTRICT          75748 non-null  str    
 2   VEHICLE AT FAULT  75748 non-null  str    
 3   VICTIM            75748 non-null  str    
 4   TYPE OF ACCIDENT  75748 non-null  str    
 5   # INJURED         75748 non-null  int64  
 6   # KILLED          75748 non-null  int64  
 7   Unnamed: 7        0 non-null      float64
 8   Unnamed: 8        0 non-null      float64
 9   Unnamed: 9        1 non-null      str    
dtypes: float64(2), int64(3), str(5)
memory usage: 5.8 MB


In [8]:
# Statistical summary
df.describe(include="all")

,YEAR,DISTRICT,VEHICLE AT FAULT,VICTIM,TYPE OF ACCIDENT,# INJURED,# KILLED,Unnamed: 7,Unnamed: 8,Unnamed: 9
count,75748.000000,75748,75748,75748,75748,75748.000000,75748.000000,0.0,0.0,1
unique,NaN,13,34,41,3,NaN,NaN,NaN,NaN,1
top,NaN,SOUTH EAST DELHI,PVT CAR,PEDESTRIAN,SIMPLE ACCIDENT,NaN,NaN,NaN,NaN,
freq,NaN,10096,22043,31872,55883,NaN,NaN,NaN,NaN,1
mean,2012.446863,NaN,NaN,NaN,NaN,0.955682,0.248640,NaN,NaN,NaN
std,2.868879,NaN,NaN,NaN,NaN,0.840229,0.450093,NaN,NaN,NaN
min,2008.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN
25%,2010.000000,NaN,NaN,NaN,NaN,1.000000,0.000000,NaN,NaN,NaN
50%,2013.000000,NaN,NaN,NaN,NaN,1.000000,0.000000,NaN,NaN,NaN
75%,2015.000000,NaN,NaN,NaN,NaN,1.000000,0.000000,NaN,NaN,NaN


## 3. Data Cleaning

Cleaned the dataset by:
- Removing unnecessary columns
- Removing extra spaces from column names
- Checking for missing values
- Checking for duplicate records

In [9]:
df.columns = df.columns.str.strip()

In [10]:
print(df.columns.tolist())

['YEAR', 'DISTRICT', 'VEHICLE AT FAULT', 'VICTIM', 'TYPE OF ACCIDENT', '# INJURED', '# KILLED', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9']


In [11]:
## Removing unnecessary columns
df.drop(columns=["Unnamed: 7", "Unnamed: 8", "Unnamed: 9"], inplace=True)

In [12]:
print(df.columns.tolist())

['YEAR', 'DISTRICT', 'VEHICLE AT FAULT', 'VICTIM', 'TYPE OF ACCIDENT', '# INJURED', '# KILLED']


In [13]:
df.isnull().sum()

YEAR                0
DISTRICT            0
VEHICLE AT FAULT    0
VICTIM              0
TYPE OF ACCIDENT    0
# INJURED           0
# KILLED            0
dtype: int64

In [14]:
## duplicates
duplicate_count = df.duplicated().sum()
print(f"Duplicate Rows: {duplicate_count}")

Duplicate Rows: 56819


In [15]:
print("Dataset Shape:", df.shape)

Dataset Shape: (75748, 7)


# 4. Feature Engineering

Preparing the dataset for classification by:

- Creating a new target variable (`TARGET`)
- Separating features and target
- Encoding categorical features into numerical values

In [16]:
# Create binary target
df["TARGET"] = (df["# INJURED"] > 0).astype(int)

# Display first few rows
df[["# INJURED", "TARGET"]].head(10)

,# INJURED,TARGET
0,0,0
1,1,1
2,0,0
3,1,1
4,1,1
5,1,1
6,2,1
7,1,1
8,1,1
9,1,1


In [17]:
df["TARGET"].value_counts()

TARGET
1    58938
0    16810
Name: count, dtype: int64

In [18]:
X = df.drop(columns=["# INJURED", "# KILLED", "TARGET"])
y = df["TARGET"]

In [19]:
label_encoders = {}

categorical_columns = X.select_dtypes(include="object").columns

for col in categorical_columns:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col])
    label_encoders[col] = le

C:\Users\moham\AppData\Local\Temp\ipykernel_9556\1970755098.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = X.select_dtypes(include="object").columns


In [20]:
X.head()

,YEAR,DISTRICT,VEHICLE AT FAULT,VICTIM,TYPE OF ACCIDENT
0,2008,5,33,6,0
1,2008,5,33,9,2
2,2008,2,17,25,0
3,2008,1,23,25,2
4,2008,7,23,25,2


In [21]:
X.head()

,YEAR,DISTRICT,VEHICLE AT FAULT,VICTIM,TYPE OF ACCIDENT
0,2008,5,33,6,0
1,2008,5,33,9,2
2,2008,2,17,25,0
3,2008,1,23,25,2
4,2008,7,23,25,2


In [22]:
joblib.dump(label_encoders, "../models/label_encoders_classifier.pkl")

['../models/label_encoders_classifier.pkl']

# 5. Train-Test Split

The dataset is divided into training and testing sets.

- Training set (80%) is used to train the model.
- Testing set (20%) is used to evaluate the model on unseen data.

The `stratify` parameter ensures that both sets maintain the same proportion of injury and no-injury cases.

In [23]:
# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [24]:
print("Training Features:", X_train.shape)
print("Testing Features :", X_test.shape)
print("Training Labels  :", y_train.shape)
print("Testing Labels   :", y_test.shape)

Training Features: (60598, 5)
Testing Features : (15150, 5)
Training Labels  : (60598,)
Testing Labels   : (15150,)


In [25]:
print("Training Class Distribution")
print(y_train.value_counts())

print("\nTesting Class Distribution")
print(y_test.value_counts())

Training Class Distribution
TARGET
1    47150
0    13448
Name: count, dtype: int64

Testing Class Distribution
TARGET
1    11788
0     3362
Name: count, dtype: int64


# 6. Decision Tree Classifier

A Decision Tree Classifier is trained to predict whether an accident will result in injuries.

The model is evaluated using:
- Accuracy
- F1 Score
- Confusion Matrix
- Classification Report

In [26]:
# Create the Decision Tree Classifier
dt_classifier = DecisionTreeClassifier(
    random_state=42,
    max_depth=5
)

# Train the model
dt_classifier.fit(X_train, y_train)

,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",5
,"random_state random_state: int, RandomState instance or None, default=NoneControls the randomness of the estimator. The features are alwaysrandomly permuted at each split, even if ``splitter`` is set to``""best""``. When ``max_features < n_features``, the algorithm willselect ``max_features`` at random at each split before finding the bestsplit among them. But the best found split may vary across differentruns, even if ``max_features=n_features``. That is the case, if theimprovement of the criterion is identical for several splits and onesplit has to be selected at random. To obtain a deterministic behaviourduring fitting, ``random_state`` has to be fixed to an integer.See :term:`Glossary <random_state>` for details.",42
,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.",'gini'
,"splitter splitter: {""best"", ""random""}, default=""best""The strategy used to choose the split at each node. Supportedstrategies are ""best"" to choose the best split and ""random"" to choosethe best random split.",'best'
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: int, float or {""sqrt"", ""log2""}, default=NoneThe number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... note:: The search for a split does not stop until at least one valid partition of the node samples is found, even if it requires to effectively inspect more than ``max_features`` features.",None
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow a tree with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at 

In [27]:
# Predict on test data
y_pred_dt = dt_classifier.predict(X_test)

In [28]:
# Accuracy
dt_accuracy = accuracy_score(y_test, y_pred_dt)

# F1 Score
dt_f1 = f1_score(y_test, y_pred_dt)

print(f"Accuracy : {dt_accuracy:.4f}")
print(f"F1 Score : {dt_f1:.4f}")

Accuracy : 0.9601
F1 Score : 0.9737


In [29]:
# Confusion Matrix
cm = confusion_matrix(y_test, y_pred_dt)

print(cm)

[[ 3362     0]
 [  605 11183]]


In [30]:
print(classification_report(y_test, y_pred_dt))

              precision    recall  f1-score   support

           0       0.85      1.00      0.92      3362
           1       1.00      0.95      0.97     11788

    accuracy                           0.96     15150
   macro avg       0.92      0.97      0.95     15150
weighted avg       0.97      0.96      0.96     15150



In [31]:
dt_gmean = geometric_mean_score(y_test, y_pred_dt)

print(f"Accuracy : {dt_accuracy:.4f}")
print(f"F1 Score : {dt_f1:.4f}")
print(f"G-Mean   : {dt_gmean:.4f}")

Accuracy : 0.9601
F1 Score : 0.9737
G-Mean   : 0.9740


## Decision Tree Evaluation

The Decision Tree Classifier achieved strong performance on the test dataset with an **Accuracy of 96.01%**, **F1 Score of 97.37%**, and **G-Mean of 97.40%**. The confusion matrix showed **0 false positives** and only **605 false negatives**, indicating that the model correctly classified the majority of accident records. Overall, the model demonstrated excellent predictive performance and serves as a strong baseline for comparison with AdaBoost and Stacking classifiers.

## 7. AdaBoost Classifier

AdaBoost (Adaptive Boosting) is an ensemble learning algorithm that combines multiple weak learners, typically shallow decision trees, to create a stronger classifier.



In [32]:
# Create AdaBoost Classifier
ada_classifier = AdaBoostClassifier(
    n_estimators=100,
    random_state=42
)

# Train the model
ada_classifier.fit(X_train, y_train)

,"n_estimators n_estimators: int, default=50The maximum number of estimators at which boosting is terminated.In case of perfect fit, the learning procedure is stopped early.Values must be in the range `[1, inf)`.",100
,"random_state random_state: int, RandomState instance or None, default=NoneControls the random seed given at each `estimator` at eachboosting iteration.Thus, it is only used when `estimator` exposes a `random_state`.Pass an int for reproducible output across multiple function calls.See :term:`Glossary <random_state>`.",42
,"estimator estimator: object, default=NoneThe base estimator from which the boosted ensemble is built.Support for sample weighting is required, as well as proper``classes_`` and ``n_classes_`` attributes. If ``None``, thenthe base estimator is :class:`~sklearn.tree.DecisionTreeClassifier`initialized with `max_depth=1`... versionadded:: 1.2 `base_estimator` was renamed to `estimator`.",None
,"learning_rate learning_rate: float, default=1.0Weight applied to each classifier at each boosting iteration. A higherlearning rate increases the contribution of each classifier. There isa trade-off between the `learning_rate` and `n_estimators` parameters.Values must be in the range `(0.0, inf)`.",1.0
Name,Type,Value
"classes_ classes_: ndarray of shape (n_classes,)The classes labels.","ndarray[int64](2,)","[0,1]"
estimator_ estimator_: estimatorThe base estimator from which the ensemble is grown... versionadded:: 1.2 `base_estimator_` was renamed to `estimator_`.,DecisionTreeClassifier,DecisionTreeC...r(max_depth=1)
estimator_errors_ estimator_errors_: ndarray of floatsClassification error for each estimator in the boostedensemble.,"ndarray[float64](100,)","[0.04,0.12,0.28,...,0.48,0.49,0.49]"
estimator_weights_ estimator_weights_: ndarray of floatsWeights for each estimator in the boosted ensemble.,"ndarray[float64](100,)","[3.17,2.03,0.93,...,0.08,0.03,0.03]"
estimators_ estimators_: list of classifiersThe collection of fitted sub-estimators.,list,"[DecisionTreeC...te=1608637542), DecisionTreeC...te=1273642419), DecisionTreeC...te=1935803228), DecisionTreeC...ate=787846414), ...]"
"feature_importances_ feature_importances_: ndarray of shape (n_features,)The impurity-based feature importances if supported by the``estimator`` (when based on decision trees).Warning: impurity-based feature importances can be misleading forhigh cardinality features (many unique values). See:func:`sklearn.inspection.permutation_importance` as an alternative.","ndarray[float64](5,)","[0.02,0. ,0.02,0.05,0.91]"


In [33]:
# Predict on test data
y_pred_ada = ada_classifier.predict(X_test)

In [34]:
# Accuracy
ada_accuracy = accuracy_score(y_test, y_pred_ada)

# F1 Score
ada_f1 = f1_score(y_test, y_pred_ada)

# G-Mean
ada_gmean = geometric_mean_score(y_test, y_pred_ada)

print(f"Accuracy : {ada_accuracy:.4f}")
print(f"F1 Score : {ada_f1:.4f}")
print(f"G-Mean   : {ada_gmean:.4f}")

Accuracy : 0.9601
F1 Score : 0.9737
G-Mean   : 0.9740


In [35]:
cm_ada = confusion_matrix(y_test, y_pred_ada)

print(cm_ada)

[[ 3362     0]
 [  605 11183]]


In [36]:
print(classification_report(y_test, y_pred_ada))

              precision    recall  f1-score   support

           0       0.85      1.00      0.92      3362
           1       1.00      0.95      0.97     11788

    accuracy                           0.96     15150
   macro avg       0.92      0.97      0.95     15150
weighted avg       0.97      0.96      0.96     15150



## AdaBoost Evaluation

The AdaBoost Classifier achieved an **Accuracy of 96.01%**, an **F1 Score of 97.37%**, and a **G-Mean of 97.40%** on the test dataset. The confusion matrix showed **0 false positives** and **605 false negatives**, producing the same classification performance as the Decision Tree Classifier. This indicates that AdaBoost did not provide a measurable improvement on this dataset, suggesting that the Decision Tree had already learned the underlying patterns effectively.

## 8. Random forest Classifier

In [37]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    confusion_matrix,
    classification_report
)
from imblearn.metrics import geometric_mean_score

In [38]:
rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf_model.fit(X_train, y_train)

,"random_state random_state: int, RandomState instance or None, default=NoneControls both the randomness of the bootstrapping of the samples usedwhen building trees (if ``bootstrap=True``) and the sampling of thefeatures to consider when looking for the best split at each node(if ``max_features < n_features``).See :term:`Glossary <random_state>` for details.",42
,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",100
,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.Note: This parameter is tree-specific.",'gini'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: {""sqrt"", ""log2"", None}, int or float, default=""sqrt""The number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... versionchanged:: 1.1 The default of `max_features` changed from `""auto""` to `""sqrt""`.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",'sqrt'
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow trees with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the current node, ``N_t_L`` is the number of samples in theleft child, and ``N_t_R`` is the number of samples in the right child.``N``, ``N_t``, ``N_t_R`` and ``N_t_L`` all refer to the weighted sum,if ``sample_weight`` is passed... versionadded:: 0.19",0.0
,"bootstrap bootstr

In [39]:
y_pred_rf = rf_model.predict(X_test)

In [40]:
accuracy = accuracy_score(y_test, y_pred_rf)
f1 = f1_score(y_test, y_pred_rf)
gmean = geometric_mean_score(y_test, y_pred_rf)

print(f"Accuracy: {accuracy:.4f}")
print(f"F1 Score: {f1:.4f}")
print(f"G-Mean: {gmean:.4f}")

print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred_rf))

print("\nClassification Report")
print(classification_report(y_test, y_pred_rf))

Accuracy: 0.9525
F1 Score: 0.9691
G-Mean: 0.9492

Confusion Matrix
[[ 3171   191]
 [  528 11260]]

Classification Report
              precision    recall  f1-score   support

           0       0.86      0.94      0.90      3362
           1       0.98      0.96      0.97     11788

    accuracy                           0.95     15150
   macro avg       0.92      0.95      0.93     15150
weighted avg       0.96      0.95      0.95     15150



### Random Forest Evaluation

The Random Forest Classifier was trained and evaluated on the accident dataset to classify whether an accident would result in injuries. Random Forest is an ensemble learning algorithm that builds multiple decision trees using different subsets of the training data and combines their predictions through majority voting to improve generalization and reduce overfitting.

The model achieved the following performance:

- Accuracy: **95.25%**
- F1 Score: **96.91%**
- G-Mean: **94.92%**

The confusion matrix indicates that the model correctly classified most accident records, with **3,171 True Negatives**, **11,260 True Positives**, **191 False Positives**, and **528 False Negatives**.

Although the Random Forest Classifier demonstrated strong classification performance, its Accuracy, F1 Score, and G-Mean were slightly lower than those achieved by the Decision Tree and AdaBoost classifiers on this dataset. Therefore, while Random Forest proved to be an effective classifier, it was not selected as the best-performing model for this project. The results obtained from this model will be compared with the remaining classifiers to identify the most suitable model for accident injury prediction.

# 9. Support Vector Machine Classifier

In [41]:
from sklearn.svm import LinearSVC
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    confusion_matrix,
    classification_report
)
from imblearn.metrics import geometric_mean_score

In [42]:
svm_model = LinearSVC(
    random_state=42,
    max_iter=5000
)

svm_model.fit(X_train, y_train)

,"random_state random_state: int, RandomState instance or None, default=NoneControls the pseudo random number generation for shuffling the data forthe dual coordinate descent (if ``dual=True``). When ``dual=False`` theunderlying implementation of :class:`LinearSVC` is not random and``random_state`` has no effect on the results.Pass an int for reproducible output across multiple function calls.See :term:`Glossary <random_state>`.",42
,"max_iter max_iter: int, default=1000The maximum number of iterations to be run.",5000
,"penalty penalty: {'l1', 'l2'}, default='l2'Specifies the norm used in the penalization. The 'l2'penalty is the standard used in SVC. The 'l1' leads to ``coef_``vectors that are sparse.",'l2'
,"loss loss: {'hinge', 'squared_hinge'}, default='squared_hinge'Specifies the loss function. 'hinge' is the standard SVM loss(used e.g. by the SVC class) while 'squared_hinge' is thesquare of the hinge loss. The combination of ``penalty='l1'``and ``loss='hinge'`` is not supported.",'squared_hinge'
,"dual dual: ""auto"" or bool, default=""auto""Select the algorithm to either solve the dual or primaloptimization problem. Prefer dual=False when n_samples > n_features.`dual=""auto""` will choose the value of the parameter automatically,based on the values of `n_samples`, `n_features`, `loss`, `multi_class`and `penalty`. If `n_samples` < `n_features` and optimizer supportschosen `loss`, `multi_class` and `penalty`, then dual will be set to True,otherwise it will be set to False... versionchanged:: 1.3 The `""auto""` option is added in version 1.3 and will be the default in version 1.5.",'auto'
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"C C: float, default=1.0Regularization parameter. The strength of the regularization isinversely proportional to C. Must be strictly positive.For an intuitive visualization of the effects of scalingthe regularization parameter C, see:ref:`sphx_glr_auto_examples_svm_plot_svm_scale_c.py`.",1.0
,"multi_class multi_class: {'ovr', 'crammer_singer'}, default='ovr'Determines the multi-class strategy if `y` contains more thantwo classes.``""ovr""`` trains n_classes one-vs-rest classifiers, while``""crammer_singer""`` optimizes a joint objective over all classes.While `crammer_singer` is interesting from a theoretical perspectiveas it is consistent, it is seldom used in practice as it rarely leadsto better accuracy and is more expensive to compute.If ``""crammer_singer""`` is chosen, the options loss, penalty and dualwill be ignored.",'ovr'
,"fit_intercept fit_intercept: bool, default=TrueWhether or not to fit an intercept. If set to True, the feature vectoris extended to include an intercept term: `[x_1, ..., x_n, 1]`, where1 corresponds to the intercept. If set to False, no intercept will beused in calculations (i.e. data is expected to be already centered).",True
,"intercept_scaling intercept_scaling: float, default=1.0When `fit_intercept` is True, the instance vector x becomes ``[x_1,..., x_n, intercept_scaling]``, i.e. a ""synthetic"" feature with aconstant value equal to `intercept_scaling` is appended to the instancevector. The intercept becomes intercept_scaling * synthetic featureweight. Note that liblinear internally penalizes the intercept,treating it like any other term in the feature vector. To reduce theimpact of the regularization on the intercept, the `intercept_scaling`parameter can be set to a value greater than 1; the higher the value of`intercept_scaling`, the lower the impact of regularization on it.Then, the weights become `[w_x_1, ..., w_x_n,w_intercept*intercept_scaling]`, where `w_x_1, ..., w_x_n` representthe feature weights and the intercept weight is scaled by`intercept_scaling`. This scaling allows the intercept term to have adifferent regularization behavior compared to the other features.",1
,"class_weight class_weight: dict or 'balanced', default=NoneSet the parameter C of class i to ``class_weight[i]*C`` forSVC. If not given, all classes are su

In [43]:
y_pred_svm = svm_model.predict(X_test)

In [44]:
accuracy = accuracy_score(y_test, y_pred_svm)
f1 = f1_score(y_test, y_pred_svm)
gmean = geometric_mean_score(y_test, y_pred_svm)

print(f"Accuracy: {accuracy:.4f}")
print(f"F1 Score: {f1:.4f}")
print(f"G-Mean: {gmean:.4f}")

print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred_svm))

print("\nClassification Report")
print(classification_report(y_test, y_pred_svm))

Accuracy: 0.9418
F1 Score: 0.9621
G-Mean: 0.9329

Confusion Matrix
[[ 3084   278]
 [  604 11184]]

Classification Report
              precision    recall  f1-score   support

           0       0.84      0.92      0.87      3362
           1       0.98      0.95      0.96     11788

    accuracy                           0.94     15150
   macro avg       0.91      0.93      0.92     15150
weighted avg       0.94      0.94      0.94     15150



## Support Vector Machine (SVM) Evaluation

The Support Vector Machine (SVM) classifier was trained and evaluated on the accident dataset to classify whether an accident would result in injuries. SVM is a supervised machine learning algorithm that finds the optimal hyperplane to separate different classes while maximizing the margin between them. For this project, a Linear Support Vector Machine (LinearSVC) was used due to its efficiency on large datasets.

The model achieved:

- Accuracy: 94.18%
- F1 Score: 96.21%
- G-Mean: 93.29%

The confusion matrix indicates:

- 3084 True Negatives
- 11184 True Positives
- 278 False Positives
- 604 False Negatives

Although the SVM classifier produced good classification performance with a high F1 Score, its overall Accuracy and G-Mean were lower than those of the Decision Tree and AdaBoost classifiers. Therefore, it was not selected as the best-performing model for this accident prediction project.

# 10. CatBoost Classifier

In [45]:
from catboost import CatBoostClassifier
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    confusion_matrix,
    classification_report
)
from imblearn.metrics import geometric_mean_score

In [46]:
cat_model = CatBoostClassifier(
    iterations=300,
    learning_rate=0.1,
    depth=6,
    random_seed=42,
    verbose=0
)

cat_model.fit(X_train, y_train)

CatBoostClassifier(depth=6, iterations=300, learning_rate=0.1, random_seed=42, verbose=0)

In [47]:
y_pred_cat = cat_model.predict(X_test)

In [48]:
accuracy = accuracy_score(y_test, y_pred_cat)
f1 = f1_score(y_test, y_pred_cat)
gmean = geometric_mean_score(y_test, y_pred_cat)

print(f"Accuracy: {accuracy:.4f}")
print(f"F1 Score: {f1:.4f}")
print(f"G-Mean: {gmean:.4f}")

print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred_cat))

print("\nClassification Report")
print(classification_report(y_test, y_pred_cat))

Accuracy: 0.9591
F1 Score: 0.9731
G-Mean: 0.9691

Confusion Matrix
[[ 3320    42]
 [  578 11210]]

Classification Report
              precision    recall  f1-score   support

           0       0.85      0.99      0.91      3362
           1       1.00      0.95      0.97     11788

    accuracy                           0.96     15150
   macro avg       0.92      0.97      0.94     15150
weighted avg       0.96      0.96      0.96     15150



## Catboost Classifier Evaluation 

Accuracy: 0.9591
F1 Score: 0.9731
G-Mean: 0.9691

Confusion Matrix
[[ 3320    42]
 [  578 11210]]

Classification Report
              precision    recall  f1-score   support

           0       0.85      0.99      0.91      3362
           1       1.00      0.95      0.97     11788

    accuracy                           0.96     15150
   macro avg       0.92      0.97      0.94     15150
weighted avg       0.96      0.96      0.96     15150


# 10. Stacking Classifier

The Stacking Classifier is an ensemble learning technique that combines the predictions of multiple base classifiers using a meta-classifier. In this project, a Decision Tree Classifier and an AdaBoost Classifier are used as the base learners, while Logistic Regression is used as the final estimator. The model is evaluated using Accuracy, F1 Score, G-Mean, Confusion Matrix, and Classification Report.

In [49]:
## IMPORTING 
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression

In [50]:
# Base models
estimators = [
    ("decision_tree", DecisionTreeClassifier(max_depth=5, random_state=42)),
    ("adaboost", AdaBoostClassifier(n_estimators=100, random_state=42)),
    ("random_forest", RandomForestClassifier(n_estimators=100, random_state=42)),
    ("catboost", CatBoostClassifier(
        iterations=300,
        learning_rate=0.1,
        depth=6,
        random_seed=42,
        verbose=0
    ))
]
# Stacking Classifier
stack_classifier = StackingClassifier(
    estimators=estimators,
    final_estimator=LogisticRegression(max_iter=1000),
    cv=5,
    n_jobs=-1
)

# Train the model
stack_classifier.fit(X_train, y_train)

,"estimators estimators: list of (str, estimator)Base estimators which will be stacked together. Each element of thelist is defined as a tuple of string (i.e. name) and an estimatorinstance. An estimator can be set to 'drop' using `set_params`.The type of estimator is generally expected to be a classifier.However, one can pass a regressor for some use case (e.g. ordinalregression).","[('decision_tree', ...), ('adaboost', ...), ...]"
,"final_estimator final_estimator: estimator, default=NoneA classifier which will be used to combine the base estimators.The default classifier is a:class:`~sklearn.linear_model.LogisticRegression`.",LogisticRegre...max_iter=1000)
,"cv cv: int, cross-validation generator, iterable, or ""prefit"", default=NoneDetermines the cross-validation splitting strategy used in`cross_val_predict` to train `final_estimator`. Possible inputs forcv are:* None, to use the default 5-fold cross validation,* integer, to specify the number of folds in a (Stratified) KFold,* An object to be used as a cross-validation generator,* An iterable yielding train, test splits,* `""prefit""`, to assume the `estimators` are prefit. In this case, the estimators will not be refitted.For integer/None inputs, if the estimator is a classifier and y iseither binary or multiclass,:class:`~sklearn.model_selection.StratifiedKFold` is used.In all other cases, :class:`~sklearn.model_selection.KFold` is used.These splitters are instantiated with `shuffle=False` so the splitswill be the same across calls.Refer :ref:`User Guide <cross_validation>` for the variouscross-validation strategies that can be used here.If ""prefit"" is passed, it is assumed that all `estimators` havebeen fitted already. The `final_estimator_` is trained on the `estimators`predictions on the full training set and are **not** cross validatedpredictions. Please note that if the models have been trained on the samedata to train the stacking model, there is a very high risk of overfitting... versionadded:: 1.1 The 'prefit' option was added in 1.1.. note:: A larger number of split will provide no benefits if the number of training samples is large enough. Indeed, the training time will increase. ``cv`` is not used for model evaluation but for prediction.",5
,"n_jobs n_jobs: int, default=NoneThe number of jobs to run in parallel for `fit` of all `estimators`.`None` means 1 unless in a `joblib.parallel_backend` context. -1 meansusing all processors. See :term:`Glossary <n_jobs>` for more details.",-1
,"stack_method stack_method: {'auto', 'predict_proba', 'decision_function', 'predict'}, default='auto'Methods called for each base estimator. It can be:* if 'auto', it will try to invoke, for each estimator, `'predict_proba'`, `'decision_function'` or `'predict'` in that order.* otherwise, one of `'predict_proba'`, `'decision_function'` or `'predict'`. If the method is not implemented by the estimator, it will raise an error.",'auto'
,"passthrough passthrough: bool, default=FalseWhen False, only the predictions of estimators will be used astraining data for `final_estimator`. When True, the`final_estimator` is trained on the predictions as well as theoriginal training data.",False
,"verbose verbose: int, default=0Verbosity level.",0
Name,Type,Value
"classes_ classes_: ndarray of shape (n_classes,) or list of ndarray if `y` is of type `""multilabel-indicator""`.Class labels.","ndarray[int64](2,)","[0,1]"
"estimators_ estimators_: list of estimatorsThe elements of the `estimators` parameter, having been fitted on thetraining data. If an estimator has been set to `'drop'`, itwill not appear in `estimators_`. When `cv=""prefit""`, `estimators_`is set to `estimators` and is not fitted again.",list,"[DecisionTreeC...ndom_state=42), AdaBoostClass...ndom_state=42), RandomForestC...ndom_state=42), CatBoostClass...42, verbose=0)]"
"feature_names_in_ feature_names_in_: ndarray of shape (`n_features_in_`,)Names of features seen during :term:`fit`. Only defined if theunderlying estimators ex

In [51]:
# Predict on test data
y_pred_stack = stack_classifier.predict(X_test)

In [52]:
# Accuracy
stack_accuracy = accuracy_score(y_test, y_pred_stack)

# F1 Score
stack_f1 = f1_score(y_test, y_pred_stack)

# G-Mean
stack_gmean = geometric_mean_score(y_test, y_pred_stack)

print(f"Accuracy : {stack_accuracy:.4f}")
print(f"F1 Score : {stack_f1:.4f}")
print(f"G-Mean   : {stack_gmean:.4f}")

Accuracy : 0.9591
F1 Score : 0.9731
G-Mean   : 0.9686


In [53]:
cm_stack = confusion_matrix(y_test, y_pred_stack)

print(cm_stack)

[[ 3315    47]
 [  572 11216]]


In [54]:
print(classification_report(y_test, y_pred_stack))

              precision    recall  f1-score   support

           0       0.85      0.99      0.91      3362
           1       1.00      0.95      0.97     11788

    accuracy                           0.96     15150
   macro avg       0.92      0.97      0.94     15150
weighted avg       0.96      0.96      0.96     15150



## Stacking Classifier Evaluation

The Stacking Classifier was developed by combining **Decision Tree, AdaBoost, Random Forest, and CatBoost** as the base learners, while **Logistic Regression** was used as the meta-classifier. The purpose of stacking was to improve classification performance by integrating the predictions of multiple machine learning models into a single ensemble.

The model achieved an **Accuracy of 95.91%**, an **F1 Score of 97.31%**, and a **G-Mean of 96.86%**, indicating excellent overall classification performance. The confusion matrix showed that the model correctly classified **3,315 non-injury cases** and **11,216 injury cases**, while incorrectly classifying **47 non-injury cases as injury** and **572 injury cases as non-injury**.

The classification report shows that the model achieved a **precision of 85%**, **recall of 99%**, and **F1 Score of 91%** for the non-injury class. For the injury class, it achieved **100% precision**, **95% recall**, and an **F1 Score of 97%**. The weighted average **F1 Score of 96%** demonstrates that the classifier maintained strong performance despite the class imbalance in the dataset.

Although the Stacking Classifier achieved excellent predictive performance, it did not outperform the standalone Decision Tree and AdaBoost classifiers. This is because the ensemble consisted primarily of tree-based models, which produced highly similar predictions. As a result, the Logistic Regression meta-classifier had limited additional information to learn from, resulting in only marginal improvements over individual classifiers. Nevertheless, the Stacking Classifier remains a robust ensemble model and demonstrates the effectiveness of combining multiple classifiers for accident injury prediction.

In [55]:
joblib.dump(dt_classifier,
            "../models/decision_tree_classifier.pkl")

['../models/decision_tree_classifier.pkl']